###############################################################################
##
##Licensed Materials - Property of IBM
##
##(C) Copyright IBM Corp. 2022, 2023. All Rights Reserved.
##
##US Government Users Restricted Rights - Use, duplication or
##disclosure restricted by GSA ADP Schedule Contract with IBM Corp.
##
###############################################################################
##
##============================================================================================
## DISCLAIMER
## These configurations are not indicated or intended to be valid for production environments.
## The purpose is purely educational.
##============================================================================================
##
## DEPLOYMENT CONTENTS
## 
## patterns: foundation,workflow
###############################################################################
apiVersion: icp4a.ibm.com/v1
kind: ICP4ACluster
metadata:
  name: ${CP4BA_INST_CR_NAME}
  namespace: ${CP4BA_INST_NAMESPACE}
  labels:
    app.kubernetes.io/instance: ibm-dba
    app.kubernetes.io/managed-by: ibm-dba
    app.kubernetes.io/name: ibm-dba
    release: "23.0.2"
  annotations:
    kubernetes.io/description: "${CP4BA_INST_DESCRIPTION}"
spec:

  appVersion: "23.0.2"
  ibm_license: accept

  shared_configuration:
    sc_deployment_fncm_license: "non-production"
    sc_deployment_baw_license: "non-production"
    sc_deployment_license: "non-production"
    sc_deployment_context: "CP4A"
    sc_image_repository: cp.icr.io
    root_ca_secret: icp4a-root-ca
    sc_deployment_patterns: "${CP4BA_INST_DEPL_PATTERNS}"
    sc_optional_components: "${CP4BA_INST_OPT_COMPONENTS}"
    sc_deployment_type: "Production"
    sc_deployment_platform: "${CP4BA_INST_PLATFORM}"
    sc_deployment_profile_size: "${CP4BA_INST_DEPL_PROFILE_SIZE}"
    sc_ingress_enable: false
    trusted_certificate_list: []
    storage_configuration:
      sc_dynamic_storage_classname: "${CP4BA_INST_SC_FILE}"
      sc_slow_file_storage_classname: "${CP4BA_INST_SC_FILE}"
      sc_medium_file_storage_classname: "${CP4BA_INST_SC_FILE}"
      sc_fast_file_storage_classname: "${CP4BA_INST_SC_FILE}"
      sc_block_storage_classname: "${CP4BA_INST_SC_BLOCK}"
    sc_iam:
      default_admin_username: "${CP4BA_INST_IAM_ADMIN_USER}"
    enable_fips: false
    #sc_run_as_user:
    sc_egress_configuration:
      # set false to enable outbout access
      sc_restricted_internet_access: false
    #  sc_api_namespace:
    #  sc_api_port:
    #  sc_dns_namespace:
    #  sc_dns_port:
    #sc_drivers_url:
    sc_content_initialization: true
    sc_content_verification: false
    encryption_key_secret: ibm-iaws-shared-key-secret
    image_pull_secrets:
      - ibm-entitlement-key
    no_log: false
    show_sensitive_log: true

  ldap_configuration:
    lc_selected_ldap_type: "Custom"
    lc_ldap_server: "${CP4BA_INST_LDAP_HOST}"
    lc_ldap_port: "${CP4BA_INST_LDAP_PORT}"
    lc_bind_secret: "${CP4BA_INST_LDAP_SECRET}"
    lc_ldap_base_dn: "${CP4BA_INST_LDAP_BASE_DOMAIN}"
    lc_ldap_ssl_enabled: false
    lc_ldap_ssl_secret_name: ""
    lc_ldap_user_name_attribute: "*:cn"
    lc_ldap_user_display_name_attr: "cn"
    lc_ldap_group_base_dn: "${CP4BA_INST_LDAP_BASE_DOMAIN}"
    lc_ldap_group_name_attribute: "*:cn"
    lc_ldap_group_display_name_attr: "cn"
    lc_ldap_group_membership_search_filter: "(&(cn=%v)(objectclass=groupOfNames))"
    lc_ldap_group_member_id_map: "memberof:member"
    lc_ldap_recursive_search: true
    lc_enable_pagination: false
    lc_pagination_size: 4500     
    custom:
      lc_user_filter: "(&(cn=%v)(objectclass=person))"
      lc_group_filter: "(&(cn=%v)(objectclass=groupOfNames))"

  datasource_configuration:
    dc_ssl_enabled: false

    dc_icn_datasource:
      dc_database_type: "postgresql"
      dc_common_icn_datasource_name: "ECMClientDS"
      database_servername: "${CP4BA_INST_DB_SERVER_NAME}"
      database_port: "${CP4BA_INST_DB_SERVER_PORT}"
      database_name: "${CP4BA_INST_DB_FAMILY_PREFIX}_icn"
      database_ssl_secret_name: ""
      #dc_hadr_validation_timeout: 15
      #dc_hadr_standby_servername: ""
      #dc_hadr_standby_port: ""
      #dc_hadr_retry_interval_for_client_reroute: 15
      #dc_hadr_max_retries_for_client_reroute: 3

  # IBM Application Engine configuration
  #application_engine_configuration:
  #  - name: ${CP4BA_INST_AE_1_NAME} 
  #    admin_secret_name: "${CP4BA_INST_AE_1_AD_SECRET_NAME}"
  #    admin_user: "${CP4BA_INST_AE_1_ADMIN_USER}"
  #    database:
  #      host: "${CP4BA_INST_AE_1_DB_HOST}"
  #      port: "${CP4BA_INST_AE_1_DB_PORT}"      
  #      name: "${CP4BA_INST_AE_1_DB_NAME}"
  #      type: postgresql
  #      enable_ssl: false
  #      db_cert_secret_name: ""
  #    session:
  #      use_external_store: false

  # IBM Business Automation Workflow configuration
  baw_configuration:
    - name: ${CP4BA_INST_BAW_1_NAME} 
      capabilities: "workflow"
      host_federated_portal: false
      admin_user: "${CP4BA_INST_PAKBA_ADMIN_USER}"
      database:
        enable_ssl: false
        db_cert_secret_name: ""
        type: "postgresql"
        server_name: "${CP4BA_INST_BAW_1_DB_HOST}"
        port: "5452"
        database_name: "${CP4BA_INST_BAW_1_DB_NAME}"
        secret_name: "${CP4BA_INST_BAW_1_DB_SECRET}"
        use_custom_jdbc_drivers: false
        cm_max_pool_size: ${CP4BA_INST_BAW_1_MAX_POOL_SIZE}
      #content_integration:
      #  domain_name: "P8DOMAIN"
      #  object_store_name: "BAWINS1DOCS"
      #case:
      #  domain_name: "P8DOMAIN"
      #  object_store_name_dos: "BAWINS1DOS"
      #  tos_list:
      #    - object_store_name: "BAWINS1TOS"
      security_context:
        selinux_options:
        fs_groupchangepolicy:
      # Production, Staging, Test, Development
      env_type: Test
      replicas: ${CP4BA_INST_BAW_1_REPLICAS}
      resources:
        limits:
          cpu: "${CP4BA_INST_BAW_1_LIMITS_CPU}"
          memory: "${CP4BA_INST_BAW_1_LIMITS_MEMORY}"
        requests:
          cpu: "500m"
          memory: "1048Mi"
      ## Resource configuration for init job
      resources_init:
        limits:
          ## CPU limit for init job containers.
          cpu: "${CP4BA_INST_BAW_1_LIMITS_CPU}"
          ## Memory limit for init job containers.
          memory: 512Mi
        requests:
          ## Requested amount of CPU for init job containers.
          cpu: "200m"
          ## Requested amount of memory for init job containers.
          memory: 128Mi

      ## Resource configuration for heavy init job such as database init job
      resources_init_heavy_job:
        limits:
          ## CPU limit for Workflow Server database init job container.
          cpu: "${CP4BA_INST_BAW_1_LIMITS_CPU}"
          ## Memory limit for Workflow Server database init job container.
          memory: 2048Mi
        requests:
          ## Requested amount of CPU for Workflow Server database init job container.
          cpu: "500m"
          ## Requested amount of memory for Workflow Server database init job container.
          memory: 512Mi
      logs:
        trace_specification: "${CP4BA_INST_BAW_1_LOGS_TRACE}"

      # Set PFS information if you have PFS installed and want to federate Workflow Server to it.
      #process_federation_server:
      #  hostname:
      #  port:
      #  context_root_prefix:

      ### federation config
      #federation_config:
      #  workflow_server:
      #      ## Number of primary shards of the Elasticsearch index used to store Workflow Server data.
      #      index_number_of_shards: 3
      #      ## Number of shard replicas of the Elasticsearch index used to store Workflow Server data.
      #      index_number_of_replicas: 1
      #  case_manager:
      #        ## Case Manager object store name.
      #      - object_store_name: BAWINS1TOS
      #        ## Number of primary shards of the Elasticsearch index used to store Case Manager object store data.
      #        index_number_of_shards: 3
      #        ## Number of shard replicas of the Elasticsearch index used to store Case Manager object store data.
      #        index_number_of_replicas: 1

      #tls:
      #  ## Workflow Server TLS secret that contains tls.key and tls.crt.
      #  ## If you want to use a customized Workflow Server TLS certificate, ensure it is signed by the CA in shared_configuration.root_ca_secret.
      #  ## If you do not want to use a customized Workflow Server TLS certificate, leave it empty.
      #  tls_secret_name:
      #  ## Workflow Server TLS trust list.
      #  ## You might specify a list of secrets, every secret stores a trusted CA
      #  ## Use command `kubectl create secret generic baw_custom_trust_ca_secret1 --from-file=tls.crt=./ca1.crt` to generate the secret.
      #  tls_trust_list:
      #  ## Secret to store your custom trusted keystore (optional). The type for the keystore must be JKS or PKCS12. All certificates from the keystore are imported into the trust keystore of the Workflow Server.
      #  ## When FIPS mode is enabled, you cannot use this parameter, and external sourced trust stores are not supported.
      #  ## You might run the following sample command to create the secret:
      #  ## `kubectl create secret generic baw_custom_trusted_keystore_secret --from-file=truststorefile=./trust.p12 --from-literal=type=PKCS12  --from-literal=password=WebAS`
      #  tls_trust_store:

      # proseguire da sezione IBM Business Automation Navigator configuration+FNCM+... / ibm_cp4a_cr_production_FC_workflow.yaml