#----------------------------------------------------------------------
# RPA section
#----------------------------------------------------------------------

export CP4BA_INST_RPA_SA="ibm-cp4ba-anyuid"

# Storage
export CP4BA_INST_RPA_PVC_NAME="mssql-data"
export CP4BA_INST_RPA_PVC_SIZE="8Gi"

# Deplyment & secret
export CP4BA_INST_RPA_DB_SECRET_NAME="rpa-mssql"
export CP4BA_INST_RPA_DB_USER="sa"
export CP4BA_INST_RPA_DB_PWD="dem0s-dem0s"
export CP4BA_INST_RPA_DB_DEPLOYMENT_NAME="rpa-mssql"
export CP4BA_INST_RPA_DB_DEPLOYMENT_LABEL="${CP4BA_INST_RPA_DB_DEPLOYMENT_NAME}"
export CP4BA_INST_RPA_DB_IMAGE="mcr.microsoft.com/mssql/server:2025-latest"

# Services
export CP4BA_INST_RPA_SERVICE_NODEPORT_NAME="rpa-mssql-service-node-port"
export CP4BA_INST_RPA_SERVICE_NAME="rpa-mssql-service"
export CP4BA_INST_RPA_NODE_PORT=31433
export CP4BA_INST_RPA_DB_PORT=1433

export CP4BA_INST_RPA_TENANT_OWNER_NAME="${CP4BA_INST_PAKBA_ADMIN_USER}"
export CP4BA_INST_RPA_TENANT_OWNER_EMAIL="${CP4BA_INST_PAKBA_ADMIN_USER}@vuxprod.net"

# smtp
export CP4BA_INST_RPA_SMTP_USER="${CP4BA_INST_PAKBA_ADMIN_USER}"
export CP4BA_INST_RPA_SMTP_PASSWORD="${CP4BA_INST_PAKBA_ADMIN_PWD}"

#------------------------------------
# (Optional) Installing the IBM Licensing operator
CP4BA_INST_LICENSING_CHANNEL=v4.2

CP4BA_INST_RPA_NAMESPACE="${CP4BA_INST_RPA_NAMESPACE:=my-rpa-standalone1}"
CP4BA_INST_RPA_CHANNEL=v3.3
CP4BA_INST_RPA_VERSION=3.3.0
CP4BA_INST_MQ_CHANNEL=v3.9

CP4BA_INST_RPA_SERVICE_NAME=rpa
CP4BA_INST_DB_RPA_NAME=SQLEXPRESS
CP4BA_INST_RPA_SERVICE_NAME="rpa-mssql-service"
CP4BA_INST_RPA_DB_PORT=1433
CP4BA_INST_RPA_DB_USER="sa"
CP4BA_INST_RPA_DB_PWD="dem0s-dem0s"
CP4BA_INST_RPA_VERIFY_DB="false"
CP4BA_INST_RPA_ADMIN_PWD="dem0s"
CP4BA_INST_RPA_INSTANCE_NAME="rpa"
CP4BA_INST_RPA_TENANT_NAME="ibm"
CP4BA_INST_RPA_MANAGED="${CP4BA_INST_RPA_MANAGED:=false}" # true for managed standalone installation, if false requires zenservice already installed
CP4BA_INST_SC_FILE="ocs-external-storagecluster-cephfs"
CP4BA_INST_SC_BLOCK="ocs-external-storagecluster-ceph-rbd"

CP4BA_INST_RPA_DB_CONN_COMM_PARAMS="Connect Timeout=30;Encrypt=False;TrustServerCertificate=False;ApplicationIntent=ReadWrite;MultiSubnetFailover=False"
CP4BA_INST_RPA_DB_CONN_PARAMS_ADDRESS="Data Source="${CP4BA_INST_RPA_SERVICE_NAME}.${CP4BA_INST_RPA_NAMESPACE}".svc.cluster.local\\"${_DB_RPA_NAME}","${CP4BA_INST_RPA_DB_PORT}";Initial Catalog=address;User ID="${CP4BA_INST_RPA_DB_USER}";Password="${CP4BA_INST_RPA_DB_PWD}";"${CP4BA_INST_RPA_DB_CONN_COMM_PARAMS}
CP4BA_INST_RPA_DB_CONN_PARAMS_AUTOMATION="Data Source="${CP4BA_INST_RPA_SERVICE_NAME}.${CP4BA_INST_RPA_NAMESPACE}".svc.cluster.local\\"${_DB_RPA_NAME}","${CP4BA_INST_RPA_DB_PORT}";Initial Catalog=automation;User ID="${CP4BA_INST_RPA_DB_USER}";Password="${CP4BA_INST_RPA_DB_PWD}";"${CP4BA_INST_RPA_DB_CONN_COMM_PARAMS}
CP4BA_INST_RPA_DB_CONN_PARAMS_KNOWLEDGE="Data Source="${CP4BA_INST_RPA_SERVICE_NAME}.${CP4BA_INST_RPA_NAMESPACE}".svc.cluster.local\\"${_DB_RPA_NAME}","${CP4BA_INST_RPA_DB_PORT}";Initial Catalog=knowledge;User ID="${CP4BA_INST_RPA_DB_USER}";Password="${CP4BA_INST_RPA_DB_PWD}";"${CP4BA_INST_RPA_DB_CONN_COMM_PARAMS}
CP4BA_INST_RPA_DB_CONN_PARAMS_WORDNET="Data Source="${CP4BA_INST_RPA_SERVICE_NAME}.${CP4BA_INST_RPA_NAMESPACE}".svc.cluster.local\\"${_DB_RPA_NAME}","${CP4BA_INST_RPA_DB_PORT}";Initial Catalog=wordnet;User ID="${CP4BA_INST_RPA_DB_USER}";Password="${CP4BA_INST_RPA_DB_PWD}";"${CP4BA_INST_RPA_DB_CONN_COMM_PARAMS}
CP4BA_INST_RPA_DB_CONN_PARAMS_AUDIT="Data Source="${CP4BA_INST_RPA_SERVICE_NAME}.${CP4BA_INST_RPA_NAMESPACE}".svc.cluster.local\\"${_DB_RPA_NAME}","${CP4BA_INST_RPA_DB_PORT}";Initial Catalog=audit;User ID="${CP4BA_INST_RPA_DB_USER}";Password="${CP4BA_INST_RPA_DB_PWD}";"${CP4BA_INST_RPA_DB_CONN_COMM_PARAMS}
