#------------------------------------
# (Optional) Installing the IBM Licensing operator
_LICENSING_CHANNEL=v4.2

_RPA_NAMESPACE="my-rpa-standalone1"
_RPA_CHANNEL=v3.3
_RPA_VERSION=3.3.0
_MQ_CHANNEL=v3.9

_RPA_SERVICE_NAME=rpa
_DB_RPA_NAME=SQLEXPRESS
_RPA_SERVICE_NAME="rpa-mssql-service"
_RPA_DB_PORT=1433
_RPA_DB_USER="sa"
_RPA_DB_PWD="dem0s-dem0s"
_RPA_VERIFY_DB="false"
_RPA_ADMIN_PWD="dem0s"
_RPA_INSTANCE_NAME="rpa"
_RPA_TENANT_NAME="ibm"
_RPA_MANAGED="${_RPA_MANAGED:=false}" # true for managed standalone installation, if false requires zenservice already installed
_SC_FILE="ocs-external-storagecluster-cephfs"
_SC_BLOCK="ocs-external-storagecluster-ceph-rbd"

_RPA_DB_CONN_COMM_PARAMS="Connect Timeout=30;Encrypt=False;TrustServerCertificate=False;ApplicationIntent=ReadWrite;MultiSubnetFailover=False"
_RPA_DB_CONN_PARAMS_ADDRESS="Data Source="${_RPA_SERVICE_NAME}.${_RPA_NAMESPACE}".svc.cluster.local\\"${_DB_RPA_NAME}","${_RPA_DB_PORT}";Initial Catalog=address;User ID="${_RPA_DB_USER}";Password="${_RPA_DB_PWD}";"${_RPA_DB_CONN_COMM_PARAMS}
_RPA_DB_CONN_PARAMS_AUTOMATION="Data Source="${_RPA_SERVICE_NAME}.${_RPA_NAMESPACE}".svc.cluster.local\\"${_DB_RPA_NAME}","${_RPA_DB_PORT}";Initial Catalog=automation;User ID="${_RPA_DB_USER}";Password="${_RPA_DB_PWD}";"${_RPA_DB_CONN_COMM_PARAMS}
_RPA_DB_CONN_PARAMS_KNOWLEDGE="Data Source="${_RPA_SERVICE_NAME}.${_RPA_NAMESPACE}".svc.cluster.local\\"${_DB_RPA_NAME}","${_RPA_DB_PORT}";Initial Catalog=knowledge;User ID="${_RPA_DB_USER}";Password="${_RPA_DB_PWD}";"${_RPA_DB_CONN_COMM_PARAMS}
_RPA_DB_CONN_PARAMS_WORDNET="Data Source="${_RPA_SERVICE_NAME}.${_RPA_NAMESPACE}".svc.cluster.local\\"${_DB_RPA_NAME}","${_RPA_DB_PORT}";Initial Catalog=wordnet;User ID="${_RPA_DB_USER}";Password="${_RPA_DB_PWD}";"${_RPA_DB_CONN_COMM_PARAMS}
_RPA_DB_CONN_PARAMS_AUDIT="Data Source="${_RPA_SERVICE_NAME}.${_RPA_NAMESPACE}".svc.cluster.local\\"${_DB_RPA_NAME}","${_RPA_DB_PORT}";Initial Catalog=audit;User ID="${_RPA_DB_USER}";Password="${_RPA_DB_PWD}";"${_RPA_DB_CONN_COMM_PARAMS}
