
###############################################################################
##
##Licensed Materials - Property of IBM
##
##(C) Copyright IBM Corp. 2023. All Rights Reserved.
##
##US Government Users Restricted Rights - Use, duplication or
##disclosure restricted by GSA ADP Schedule Contract with IBM Corp.
##
###############################################################################
##
##============================================================================================
## DISCLAIMER
## These configurations are not indicated or intended to be valid for production environments.
## The purpose is purely educational.
##============================================================================================
##
## DEPLOYMENT CONTENTS
## 
## patterns: foundation,workflow
## Content
###############################################################################
apiVersion: icp4a.ibm.com/v1
kind: Content
metadata:
  name: ${CP4BA_INST_CR_NAME}
  namespace: ${CP4BA_INST_NAMESPACE}
  labels:
    app.kubernetes.io/instance: ibm-dba-content
    app.kubernetes.io/managed-by: ibm-dba-content
    app.kubernetes.io/name: ibm-dba-content
    release: ${CP4BA_INST_APPVER}
  annotations:
    kubernetes.io/description: "${CP4BA_INST_DESCRIPTION}"
spec:

  appVersion: ${CP4BA_INST_APPVER}
  license:
    accept: true

  content_deployment_type: Production
  
  content_optional_components:
    bai: ${CP4BA_INST_CONTENT_OPTCOMPS_BAI}
    cmis: ${CP4BA_INST_CONTENT_OPTCOMPS_CMIS}
    css: ${CP4BA_INST_CONTENT_OPTCOMPS_CSS}
    iccsap: ${CP4BA_INST_CONTENT_OPTCOMPS_ICCSAP}
    ier: ${CP4BA_INST_CONTENT_OPTCOMPS_IER}
    tm: ${CP4BA_INST_CONTENT_OPTCOMPS_TM}

  shared_configuration:
    sc_deployment_fncm_license: "non-production"
    image_pull_secrets:
    - ibm-entitlement-key
    sc_image_repository: cp.icr.io
    root_ca_secret: icp4a-root-ca
    sc_run_as_user:
    sc_deployment_platform: "${CP4BA_INST_PLATFORM}"

    sc_egress_configuration:
      sc_restricted_internet_access: true
      sc_api_namespace:
      sc_api_port:
      sc_dns_namespace:
      sc_dns_port:

    trusted_certificate_list: []
    sc_drivers_url:
    sc_content_initialization: true
    sc_content_verification: false

    storage_configuration:
      sc_dynamic_storage_classname: "${CP4BA_INST_SC_FILE}"
      sc_slow_file_storage_classname: "${CP4BA_INST_SC_FILE}"
      sc_medium_file_storage_classname: "${CP4BA_INST_SC_FILE}"
      sc_fast_file_storage_classname: "${CP4BA_INST_SC_FILE}"
      sc_block_storage_classname: "${CP4BA_INST_SC_BLOCK}"

  ldap_configuration:
    lc_selected_ldap_type: "Custom"
    lc_ldap_server: "${CP4BA_INST_LDAP_HOST}"
    lc_ldap_port: "${CP4BA_INST_LDAP_PORT}"
    lc_bind_secret: "${CP4BA_INST_LDAP_SECRET}"
    lc_ldap_base_dn: "${CP4BA_INST_LDAP_BASE_DOMAIN}"
    lc_ldap_ssl_enabled: false
    lc_ldap_ssl_secret_name: ""
    lc_ldap_user_name_attribute: "*:cn"
    lc_ldap_user_display_name_attr: "cn"
    lc_ldap_group_base_dn: "${CP4BA_INST_LDAP_BASE_DOMAIN}"
    lc_ldap_group_name_attribute: "*:cn"
    lc_ldap_group_display_name_attr: "cn"
    lc_ldap_group_membership_search_filter: "(&(cn=%v)(objectclass=groupOfNames))"
    lc_ldap_group_member_id_map: "memberof:member"
    lc_ldap_recursive_search: true
    lc_enable_pagination: false
    lc_pagination_size: 4500     
    custom:
      lc_user_filter: "(&(cn=%v)(objectclass=person))"
      lc_group_filter: "(&(cn=%v)(objectclass=groupOfNames))"

  datasource_configuration:
    dc_ssl_enabled: false

    dc_gcd_datasource:
      dc_database_type: "postgresql"
      dc_common_gcd_datasource_name: "FNGCDDS"
      dc_common_gcd_xa_datasource_name: "FNGCDDSXA"
      database_servername: "${CP4BA_INST_DB_1_SERVER_NAME}"
      database_name: "${CP4BA_INST_ENV_FOR_DB_PREFIX}_gcd"
      database_port: "${CP4BA_INST_DB_SERVER_PORT}"
      database_ssl_secret_name: ""
      dc_hadr_validation_timeout: 15
      dc_hadr_standby_servername: ""
      dc_hadr_standby_port: ""
      dc_hadr_retry_interval_for_client_reroute: 15
      dc_hadr_max_retries_for_client_reroute: 3

    dc_os_datasources:
    - dc_database_type: "postgresql"
      dc_os_label: "${CP4BA_INST_DB_OS_LBL}"
      dc_common_os_datasource_name: "FNOS1DS"
      dc_common_os_xa_datasource_name: "FNOS1DSXA"
      database_servername: "${CP4BA_INST_DB_1_SERVER_NAME}"
      database_name: "${CP4BA_INST_ENV_FOR_DB_PREFIX}_os1"
      database_port: "${CP4BA_INST_DB_SERVER_PORT}"
      database_ssl_secret_name: ""
      dc_hadr_validation_timeout: 15
      dc_hadr_standby_servername: ""
      dc_hadr_standby_port: ""
      dc_hadr_retry_interval_for_client_reroute: 15
      dc_hadr_max_retries_for_client_reroute: 3

    - dc_database_type: "postgresql"
      dc_os_label: "${CP4BA_INST_DB_OS_LBL}"
      dc_common_os_datasource_name: "FNOS2DS"
      dc_common_os_xa_datasource_name: "FNOS2DSXA"
      database_servername: "${CP4BA_INST_DB_2_SERVER_NAME}"
      database_name: "${CP4BA_INST_ENV_FOR_DB_PREFIX}_os2"
      database_port: "${CP4BA_INST_DB_SERVER_PORT}"
      database_ssl_secret_name: ""
      dc_hadr_validation_timeout: 15
      dc_hadr_standby_servername: ""
      dc_hadr_standby_port: ""
      dc_hadr_retry_interval_for_client_reroute: 15
      dc_hadr_max_retries_for_client_reroute: 3

    dc_icn_datasource:
      dc_database_type: "postgresql"
      dc_common_icn_datasource_name: "ECMClientDS"
      database_servername: "${CP4BA_INST_DB_1_SERVER_NAME}"
      database_port: "${CP4BA_INST_DB_SERVER_PORT}"
      database_name: "${CP4BA_INST_ENV_FOR_DB_PREFIX}_icn"
      database_ssl_secret_name: ""
      dc_hadr_validation_timeout: 15
      dc_hadr_standby_servername: ""
      dc_hadr_standby_port: ""
      dc_hadr_retry_interval_for_client_reroute: 15
      dc_hadr_max_retries_for_client_reroute: 3

  initialize_configuration:
    ic_ldap_creation:
      ic_ldap_admin_user_name:
        - "${CP4BA_INST_PAKBA_ADMIN_USER}"
      ic_ldap_admins_groups_name:
        - "${CP4BA_INST_PAKBA_ADMIN_GROUP}"

    ic_domain_creation:
      domain_name: "P8DOMAIN"
      encryption_key: "128"

    ic_obj_store_creation:
      object_stores:
      - oc_cpe_obj_store_display_name: "OS01"
        oc_cpe_obj_store_symb_name: "OS01"
        oc_cpe_obj_store_conn:
          name: "objectstore1_connection"
          dc_os_datasource_name: "FNOS1DS"
          dc_os_xa_datasource_name: "FNOS1DSXA"
        oc_cpe_obj_store_admin_user_groups:
          - "${CP4BA_INST_PAKBA_ADMIN_USER}"
          - "${CP4BA_INST_PAKBA_ADMIN_GROUP}"
        oc_cpe_obj_store_asa_name: "${CP4BA_INST_CONTENT_OS_ASA_1_NAME}"
        oc_cpe_obj_store_asa_file_systems_storage_device_name: "${CP4BA_INST_CONTENT_OS_ASA_1_FS_DEV_NAME}"
        oc_cpe_obj_store_asa_root_dir_path: "/opt/ibm/asa/${CP4BA_INST_CONTENT_OS_ASA_1_ROOT_DIR_NAME}"

        # Workflow
        oc_cpe_obj_store_enable_content_event_emitter: false
        oc_cpe_obj_store_enable_workflow: ${CP4BA_INST_CONTENT_1_WF_ENABLE}
        oc_cpe_obj_store_workflow_locale: en
        oc_cpe_obj_store_workflow_region_number: 1
        oc_cpe_obj_store_workflow_region_name: "${CP4BA_INST_DB_TOS_REGION_NAME}"
        oc_cpe_obj_store_workflow_date_time_mask: "${CP4BA_INST_DB_TOS_DT_MASK}"
        oc_cpe_obj_store_workflow_data_tbl_space: "${CP4BA_INST_ENV_FOR_DB_PREFIX}_${CP4BA_INST_DB_TOS_SCHEMA_DATA}"
        oc_cpe_obj_store_workflow_index_tbl_space: "${CP4BA_INST_ENV_FOR_DB_PREFIX}_${CP4BA_INST_DB_TOS_SCHEMA_INDEX}"
        oc_cpe_obj_store_workflow_blob_tbl_space: "${CP4BA_INST_ENV_FOR_DB_PREFIX}_${CP4BA_INST_DB_TOS_SCHEMA_BLOB}"          
        oc_cpe_obj_store_workflow_admin_group: "${CP4BA_INST_PAKBA_ADMIN_GROUP}"
        oc_cpe_obj_store_workflow_config_group: "${CP4BA_INST_PAKBA_ADMIN_GROUP}"
        oc_cpe_obj_store_workflow_pe_conn_point_name: "pe_conn_os1"

      - oc_cpe_obj_store_display_name: "OS02"
        oc_cpe_obj_store_symb_name: "OS02"
        oc_cpe_obj_store_conn:
          name: "objectstore2_connection"
          dc_os_datasource_name: "FNOS2DS"
          dc_os_xa_datasource_name: "FNOS2DSXA"
        oc_cpe_obj_store_admin_user_groups:
          - "${CP4BA_INST_PAKBA_ADMIN_USER}"
          - "${CP4BA_INST_PAKBA_ADMIN_GROUP}"
        oc_cpe_obj_store_asa_name: "${CP4BA_INST_CONTENT_OS_ASA_2_NAME}"
        oc_cpe_obj_store_asa_file_systems_storage_device_name: "${CP4BA_INST_CONTENT_OS_ASA_2_FS_DEV_NAME}"
        oc_cpe_obj_store_asa_root_dir_path: "/opt/ibm/asa/${CP4BA_INST_CONTENT_OS_ASA_2_ROOT_DIR_NAME}"


    ic_icn_init_info:
      icn_repos:
      - add_repo_id: "demo_repo1"
        add_repo_ce_wsi_url: "https://{{ meta.name }}-cpe-stateless-svc.{{ meta.namespace }}.svc:9443/wsi/FNCEWS40MTOM/"
        add_repo_os_sym_name: "OS01"
        add_repo_os_dis_name: "OS01"
        add_repo_workflow_enable: ${CP4BA_INST_CONTENT_1_WF_ENABLE}
        add_repo_work_conn_pnt: "pe_conn_os1:1"
        add_repo_protocol: "FileNetP8WSI"

      - add_repo_id: "demo_repo2"
        add_repo_ce_wsi_url: "https://{{ meta.name }}-cpe-stateless-svc.{{ meta.namespace }}.svc:9443/wsi/FNCEWS40MTOM/"
        add_repo_os_sym_name: "OS02"
        add_repo_os_dis_name: "OS02"
        add_repo_workflow_enable: ${CP4BA_INST_CONTENT_2_WF_ENABLE}
        add_repo_work_conn_pnt: "pe_conn_os2:1"
        add_repo_protocol: "FileNetP8WSI"

      icn_desktop:
      - add_desktop_id: "demo"
        add_desktop_name: "icn_desktop"
        add_desktop_description: "This is ICN desktop"
        add_desktop_is_default: false
        add_desktop_repo_id: "demo_repo1"
        add_desktop_repo_workflow_enable: ${CP4BA_INST_CONTENT_1_WF_ENABLE}

  ecm_configuration:
    graphql:
      replica_count: ${CP4BA_INST_CONTENT_GRAPHQL_REPLICAS}
      image:
        repository: cp.icr.io/cp/cp4a/fncm/graphql
        tag: "${CP4BA_INST_APPVER}"
        pull_policy: IfNotPresent
      log:
        format: json
      resources:
        requests:
          cpu: 500m
          memory: 1536Mi
          ephemeral_storage: 1Gi
        limits:
          cpu: ${CP4BA_INST_CONTENT_GRAPHQL_LIMITS_CPU}
          memory: ${CP4BA_INST_CONTENT_GRAPHQL_LIMITS_MEMORY}
          ephemeral_storage: ${CP4BA_INST_CONTENT_GRAPHQL_LIMITS_EPHEMSTORAGE}
      auto_scaling:
        enabled: false
      graphql_production_setting:
        time_zone: Etc/UTC
        license_model: FNCM.PVUNonProd
        license: accept
        enable_graph_iql: ${CP4BA_INST_CONTENT_GRAPHQL}