/* 
Db WfPS 1
*/
DROP DATABASE IF EXISTS wfpsdb1;
CREATE DATABASE wfpsdb1;
CREATE ROLE wfps_user PASSWORD 'dem0s' CREATEDB CREATEROLE INHERIT LOGIN;
GRANT CONNECT ON DATABASE wfps_user TO public;
ALTER DATABASE wfpsdb1 OWNER TO wfps_user;
GRANT ALL PRIVILEGES ON DATABASE wfpsdb1 TO wfps_user;
CREATE SCHEMA wfpsdb1;
ALTER SCHEMA wfpsdb1 OWNER TO wfps_user;
GRANT ALL ON SCHEMA wfpsdb1 TO wfps_user;
ALTER DATABASE wfpsdb1 SET timezone TO 'Etc/UTC';

/* 
Db WfPS 2
*/
DROP DATABASE IF EXISTS wfpsdb2;
CREATE DATABASE wfpsdb2;
CREATE ROLE wfps_user PASSWORD 'dem0s' CREATEDB CREATEROLE INHERIT LOGIN;
GRANT CONNECT ON DATABASE wfps_user TO public;
ALTER DATABASE wfpsdb2 OWNER TO wfps_user;
GRANT ALL PRIVILEGES ON DATABASE wfpsdb2 TO wfps_user;
CREATE SCHEMA wfpsdb2;
ALTER SCHEMA wfpsdb2 OWNER TO wfps_user;
GRANT ALL ON SCHEMA wfpsdb2 TO wfps_user;
ALTER DATABASE wfpsdb2 SET timezone TO 'Etc/UTC';

/* 
Db WfPS 3
*/
DROP DATABASE IF EXISTS wfpsdb3;
CREATE DATABASE wfpsdb3;
CREATE ROLE wfps_user PASSWORD 'dem0s' CREATEDB CREATEROLE INHERIT LOGIN;
GRANT CONNECT ON DATABASE wfps_user TO public;
ALTER DATABASE wfpsdb3 OWNER TO wfps_user;
GRANT ALL PRIVILEGES ON DATABASE wfpsdb3 TO wfps_user;
CREATE SCHEMA wfpsdb3;
ALTER SCHEMA wfpsdb3 OWNER TO wfps_user;
GRANT ALL ON SCHEMA wfpsdb3 TO wfps_user;
ALTER DATABASE wfpsdb3 SET timezone TO 'Etc/UTC';

/* 
Db WfPS 4
*/
DROP DATABASE IF EXISTS wfpsdb4;
CREATE DATABASE wfpsdb4;
CREATE ROLE wfps_user PASSWORD 'dem0s' CREATEDB CREATEROLE INHERIT LOGIN;
GRANT CONNECT ON DATABASE wfps_user TO public;
ALTER DATABASE wfpsdb4 OWNER TO wfps_user;
GRANT ALL PRIVILEGES ON DATABASE wfpsdb4 TO wfps_user;
CREATE SCHEMA wfpsdb4;
ALTER SCHEMA wfpsdb4 OWNER TO wfps_user;
GRANT ALL ON SCHEMA wfpsdb4 TO wfps_user;
ALTER DATABASE wfpsdb4 SET timezone TO 'Etc/UTC';

/* 
Db WfPS 5
*/
DROP DATABASE IF EXISTS wfpsdb5;
CREATE DATABASE wfpsdb5;
CREATE ROLE wfps_user PASSWORD 'dem0s' CREATEDB CREATEROLE INHERIT LOGIN;
GRANT CONNECT ON DATABASE wfps_user TO public;
ALTER DATABASE wfpsdb5 OWNER TO wfps_user;
GRANT ALL PRIVILEGES ON DATABASE wfpsdb5 TO wfps_user;
CREATE SCHEMA wfpsdb5;
ALTER SCHEMA wfpsdb5 OWNER TO wfps_user;
GRANT ALL ON SCHEMA wfpsdb5 TO wfps_user;
ALTER DATABASE wfpsdb5 SET timezone TO 'Etc/UTC';

/* 
Db ZEN
*/
CREATE DATABASE zen;
CREATE USER zen_user;
GRANT CONNECT ON DATABASE zen TO public;
ALTER DATABASE zen OWNER TO zen_user;
GRANT ALL PRIVILEGES ON DATABASE zen TO zen_user;
CREATE SCHEMA watchdog;
ALTER SCHEMA watchdog OWNER TO zen_user;
GRANT ALL ON SCHEMA watchdog TO zen_user;
ALTER DATABASE zen SET timezone TO 'Etc/UTC';

/* 
Db IM
*/
CREATE DATABASE im;
CREATE USER im_user;
GRANT CONNECT ON DATABASE im TO public;
ALTER DATABASE im OWNER TO im_user;
GRANT ALL PRIVILEGES ON DATABASE im TO im_user;
ALTER DATABASE im SET timezone TO 'Etc/UTC';

/* 
Db BTS
*/
CREATE DATABASE bts;
CREATE USER bts_user;
GRANT CONNECT ON DATABASE im TO public;
ALTER DATABASE bts OWNER TO bts_user;
GRANT ALL PRIVILEGES ON DATABASE im TO bts_user;
ALTER DATABASE bts SET timezone TO 'Etc/UTC';


