CREATE ROLE §§dbCUSTOMowner§§ PASSWORD '§§dbCUSTOMowner_password§§' CREATEDB CREATEROLE INHERIT LOGIN;
CREATE DATABASE §§dbCUSTOMname§§ OWNER §§dbCUSTOMowner§§ ENCODING UTF8;
GRANT ALL PRIVILEGES ON DATABASE §§dbCUSTOMname§§ TO §§dbCUSTOMowner§§;
\c §§dbCUSTOMname§§;
CREATE SCHEMA IF NOT EXISTS §§dbCUSTOMowner§§ AUTHORIZATION §§dbCUSTOMowner§§;
GRANT ALL ON SCHEMA §§dbCUSTOMowner§§ TO §§dbCUSTOMowner§§;
